#!/usr/bin/env python3
"""Generate scav's NFC tables and conformance vectors from the Unicode UCD.

Lives beside the code it generates, and writes beside itself, because nothing
outside src/core/lang/ has any use for it. Run it through the build:

    cmake --build <dir> --target scav_core_unicode_tables

or directly, which needs no arguments because every path is script-relative:

    src/core/lang/gen_unicode_tables.py --download
    src/core/lang/gen_unicode_tables.py --ucd-dir /path/to/ucd

Text is normalized at parse (PRD 6), so NFC is a P0 dependency and it needs a
table. The output is committed, so an ordinary build needs neither the network
nor Python -- run this only when the pinned Unicode version moves, and remember
that the version is a determinism input.

Inputs (all from the same UCD release):
    UnicodeData.txt                canonical decompositions, combining classes
    DerivedNormalizationProps.txt  NFC_QC, Full_Composition_Exclusion
    NormalizationTest.txt          the conformance suite

Outputs, written next to this script:
    unicode_nfc_tables.inc         production tables
    unicode_nfc_vectors.inc        test-only conformance vectors
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

# Beside this script, and the repo root four levels up: src/core/lang/ -> repo.
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]

UNICODE_VERSION = "16.0.0"
UCD_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"
UCD_FILES = (
    "UnicodeData.txt",
    "DerivedNormalizationProps.txt",
    "NormalizationTest.txt",
)

# Hangul, composed algorithmically rather than from a table (Unicode 3.12).
HANGUL_S_BASE = 0xAC00
HANGUL_L_COUNT = 19
HANGUL_V_COUNT = 21
HANGUL_T_COUNT = 28
HANGUL_S_COUNT = HANGUL_L_COUNT * HANGUL_V_COUNT * HANGUL_T_COUNT

BANNER = """// GENERATED by gen_unicode_tables.py from Unicode {version}. Do not edit.
//
// Included by unicode_nfc.cpp, which owns the algorithm; this file is data only.
""".format(version=UNICODE_VERSION)


def fetch(ucd_dir: Path, download: bool) -> dict[str, str]:
    ucd_dir.mkdir(parents=True, exist_ok=True)
    out = {}
    for name in UCD_FILES:
        path = ucd_dir / name
        if download and not path.exists():
            print(f"fetching {name}", file=sys.stderr)
            with urllib.request.urlopen(f"{UCD_URL}/{name}", timeout=60) as r:
                path.write_bytes(r.read())
        if not path.exists():
            raise SystemExit(f"{path} not found; pass --download or --ucd-dir")
        out[name] = path.read_text(encoding="utf-8")
    return out


def parse_unicode_data(text: str) -> tuple[dict[int, int], dict[int, list[int]]]:
    """-> (combining class by codepoint, canonical decomposition by codepoint).

    Compatibility mappings carry a <tag> prefix and are not canonical, so they are
    dropped: scav normalizes to NFC, never NFKC."""
    ccc: dict[int, int] = {}
    decomp: dict[int, list[int]] = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        f = line.split(";")
        cp = int(f[0], 16)
        if (klass := int(f[3])) != 0:
            ccc[cp] = klass
        mapping = f[5].strip()
        if mapping and not mapping.startswith("<"):
            decomp[cp] = [int(x, 16) for x in mapping.split()]
    return ccc, decomp


def parse_derived_props(text: str) -> tuple[set[int], set[int]]:
    """-> (codepoints where NFC_QC is not Yes, Full_Composition_Exclusion set)."""
    qc_not_yes: set[int] = set()
    excluded: set[int] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        rng = f[0].split("..")
        lo = int(rng[0], 16)
        hi = int(rng[-1], 16)
        if f[1] == "NFC_QC" and f[2] in ("N", "M"):
            qc_not_yes.update(range(lo, hi + 1))
        elif f[1] == "Full_Composition_Exclusion":
            excluded.update(range(lo, hi + 1))
    return qc_not_yes, excluded


def full_decompose(cp: int, decomp: dict[int, list[int]]) -> list[int]:
    """Canonical decomposition is recursive; expanding here keeps the runtime a
    single lookup instead of a fixed-point loop."""
    if cp not in decomp:
        return [cp]
    out: list[int] = []
    for part in decomp[cp]:
        out.extend(full_decompose(part, decomp))
    return out


def to_ranges(codepoints: set[int]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for cp in sorted(codepoints):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def emit_array(name: str, ctype: str, values: list[str], per_line: int) -> str:
    """std::array rather than a C array: the pinned clang-tidy rejects the latter,
    and a generated file that cannot pass the project's own lint is a file
    someone will end up excluding from the lint."""
    if not values:
        # std::array<T, 0>::data() may be null, so emit one dead element and let
        # the count constant be the guard.
        return f"constexpr std::array<{ctype}, 1> {name}{{ 0 }};\n"
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("  " + " ".join(v + "," for v in values[i:i + per_line]))
    body = "\n".join(lines)
    return (f"constexpr std::array<{ctype}, {len(values)}> {name}{{\n"
            f"{body}\n}};\n")


def build_tables(ccc: dict[int, int],
                 decomp: dict[int, list[int]],
                 qc_not_yes: set[int],
                 excluded: set[int]) -> str:
    # Quick check: text is already NFC when no codepoint needs reordering
    # (ccc != 0) and none can compose or decompose (NFC_QC != Yes). Hangul
    # syllables are NFC_QC=Yes and are left alone, matching the standard.
    unsafe = set(qc_not_yes) | set(ccc)
    ranges = to_ranges(unsafe)

    ccc_keys = sorted(ccc)
    decomp_keys = sorted(decomp)

    flat: list[int] = []
    offsets: list[tuple[int, int]] = []
    for cp in decomp_keys:
        seq = full_decompose(cp, decomp)
        offsets.append((len(flat), len(seq)))
        flat.extend(seq)

    # Primary composites come from the two-codepoint canonical mappings that are
    # not composition-excluded. Singletons and non-starter-led mappings are
    # already inside Full_Composition_Exclusion, so no second filter is needed.
    pairs: list[tuple[int, int, int]] = []
    for cp in decomp_keys:
        seq = decomp[cp]
        if len(seq) == 2 and cp not in excluded:
            pairs.append((seq[0], seq[1], cp))
    pairs.sort()

    out = [BANNER, "\n"]
    out.append("// Codepoints that may need work: NFC_QC != Yes, or a non-zero\n"
               "// combining class. Everything outside these ranges is already NFC.\n")
    out.append(emit_array("NFC_UNSAFE_LO", "uint32_t",
                          [f"0x{lo:X}" for lo, _ in ranges], 8))
    out.append(emit_array("NFC_UNSAFE_HI", "uint32_t",
                          [f"0x{hi:X}" for _, hi in ranges], 8))
    out.append(f"constexpr uint32_t NFC_UNSAFE_RANGE_COUNT{{ {len(ranges)}U }};\n\n")

    out.append("// Canonical combining class, for codepoints where it is non-zero.\n")
    out.append(emit_array("CCC_KEYS", "uint32_t",
                          [f"0x{cp:X}" for cp in ccc_keys], 8))
    out.append(emit_array("CCC_VALUES", "scav_byte",
                          [str(ccc[cp]) for cp in ccc_keys], 16))
    out.append(f"constexpr uint32_t CCC_COUNT{{ {len(ccc_keys)}U }};\n\n")

    out.append("// Fully-expanded canonical decompositions, flattened.\n")
    out.append(emit_array("DECOMP_KEYS", "uint32_t",
                          [f"0x{cp:X}" for cp in decomp_keys], 8))
    out.append(emit_array("DECOMP_OFFSETS", "uint32_t",
                          [str(off) for off, _ in offsets], 12))
    out.append(emit_array("DECOMP_LENGTHS", "scav_byte",
                          [str(n) for _, n in offsets], 16))
    out.append(emit_array("DECOMP_DATA", "uint32_t",
                          [f"0x{cp:X}" for cp in flat], 8))
    out.append(f"constexpr uint32_t DECOMP_COUNT{{ {len(decomp_keys)}U }};\n\n")

    out.append("// Primary composites, keyed by (starter << 32) | combining.\n")
    out.append(emit_array("COMPOSE_KEYS", "uint64_t",
                          [f"0x{(a << 32) | b:X}ULL" for a, b, _ in pairs], 4))
    out.append(emit_array("COMPOSE_VALUES", "uint32_t",
                          [f"0x{c:X}" for _, _, c in pairs], 8))
    out.append(f"constexpr uint32_t COMPOSE_COUNT{{ {len(pairs)}U }};\n")
    return "".join(out)


# Part 1 is one row per character with a canonical mapping, and it is 85% of the
# suite. Because the tables are generated from the same UnicodeData.txt, those
# rows re-derive the table more than they exercise the algorithm, so Part 1 is
# thinned to a fixed stride plus every Hangul row -- Hangul is algorithmic rather
# than table-driven, so no table entry backs it and it has to be checked. Its
# kept rows also carry only the two composing checks. Every other part is kept
# whole with all five: those are the reordering, exclusion, PRI-29 and
# chained-composite cases the code gets wrong on its own.
PART1_STRIDE = 6
# The 11,172 precomposed Hangul syllables are all in Part 1 and are the single
# biggest block in the suite. They are uniform by construction, so a coprime
# stride walks every L / V / T position without carrying all of them.
PART1_HANGUL_STRIDE = 41
HANGUL_RANGES = ((0x1100, 0x11FF), (0xA960, 0xA97F), (0xAC00, 0xD7FF))

MAX_SEQ_LEN = 0xFF  # both lengths are packed into one uint16


def is_hangul(codepoints: list[int]) -> bool:
    return any(lo <= cp <= hi for cp in codepoints for lo, hi in HANGUL_RANGES)


def build_vectors(text: str) -> str:
    """The conformance suite as codepoint arrays.

    Only the NFC invariants are kept -- scav does not implement NFD or NFK*, so
    carrying those columns would be dead data. For each row `c1;c2;c3;c4;c5`:
    NFC(c1) == NFC(c2) == NFC(c3) == c2, and NFC(c4) == NFC(c5) == c4.

    A case is `source` then `expected` back to back in one flat array, so only
    the two lengths are stored and the offsets accumulate at read time. An
    expected length of zero means "expected equals source", which is a third of
    the suite and would otherwise be stored twice."""
    flat: list[int] = []
    lens: list[tuple[int, int]] = []
    kept: dict[int, int] = {}
    seen: set[tuple[tuple[int, ...], tuple[int, ...]]] = set()

    def add(part: int, source: list[int], expected: list[int]) -> None:
        if len(source) > MAX_SEQ_LEN or len(expected) > MAX_SEQ_LEN:
            raise SystemExit(f"sequence longer than {MAX_SEQ_LEN} does not pack")
        key = (tuple(source), tuple(expected))
        if key in seen:
            return
        seen.add(key)
        flat.extend(source)
        if source == expected:
            lens.append((len(source), 0))
        else:
            flat.extend(expected)
            lens.append((len(source), len(expected)))
        kept[part] = kept.get(part, 0) + 1

    part = -1
    row_in_part = 0
    hangul_row = 0
    for line in text.splitlines():
        if line.startswith("@Part"):
            part = int(line[5])
            row_in_part = 0
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cols = [c.strip() for c in line.split(";") if c.strip()]
        if len(cols) < 5:
            continue
        c = [[int(x, 16) for x in col.split()] for col in cols[:5]]
        row_in_part += 1
        if part == 1:
            if is_hangul(c[0]) or is_hangul(c[1]):
                hangul_row += 1
                if hangul_row % PART1_HANGUL_STRIDE != 0:
                    continue
            elif row_in_part % PART1_STRIDE != 0:
                continue
            add(part, c[0], c[1])
            add(part, c[2], c[1])
            continue
        for source in (c[0], c[1], c[2]):
            add(part, source, c[1])
        for source in (c[3], c[4]):
            add(part, source, c[3])

    tally = ", ".join(f"part{p}={n}" for p, n in sorted(kept.items()))
    out = [BANNER.replace("unicode_nfc.cpp, which owns the algorithm; this file "
                          "is data only",
                          "unicode_nfc_tests.cpp"), "\n"]
    out.append("// Unicode's NormalizationTest.txt, NFC columns only.\n")
    out.append(f"// Cases by suite part: {tally}.\n")
    out.append(emit_array("NFC_VECTOR_DATA", "uint32_t",
                          [f"0x{cp:X}" for cp in flat], 12))
    out.append("// Packed (source length << 8) | expected length, in order.\n")
    out.append(emit_array("NFC_VECTOR_LENS", "uint16_t",
                          [f"0x{(a << 8) | b:04X}" for a, b in lens], 12))
    out.append(f"constexpr uint32_t NFC_VECTOR_COUNT{{ {len(lens)}U }};\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ucd-dir", type=Path, default=REPO_ROOT / "out/ucd")
    ap.add_argument("--download", action="store_true")
    ap.add_argument("--out-dir", type=Path, default=HERE)
    args = ap.parse_args()

    ucd = fetch(args.ucd_dir, args.download)
    ccc, decomp = parse_unicode_data(ucd["UnicodeData.txt"])
    qc_not_yes, excluded = parse_derived_props(ucd["DerivedNormalizationProps.txt"])

    # Hangul is algorithmic in both directions, so a table entry would be dead
    # weight and a source of disagreement with the code path that handles it.
    for cp in range(HANGUL_S_BASE, HANGUL_S_BASE + HANGUL_S_COUNT):
        decomp.pop(cp, None)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    tables = args.out_dir / "unicode_nfc_tables.inc"
    vectors = args.out_dir / "unicode_nfc_vectors.inc"
    tables.write_text(build_tables(ccc, decomp, qc_not_yes, excluded),
                      encoding="utf-8", newline="\n")
    vectors.write_text(build_vectors(ucd["NormalizationTest.txt"]),
                       encoding="utf-8", newline="\n")
    print(f"wrote {tables} ({tables.stat().st_size} bytes)")
    print(f"wrote {vectors} ({vectors.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
