#!/usr/bin/env python3
"""Generate scav's NFC tables and conformance vectors from the Unicode UCD.

Run it through the build:

    cmake --build <dir> --target scav_core_unicode_tables

or directly; default paths are relative to the script:

    src/core/lang/gen_unicode_tables.py --download
    src/core/lang/gen_unicode_tables.py --ucd-dir /path/to/ucd

The outputs are committed. Rerun only when UNICODE_VERSION changes; the version
is a determinism input.

Inputs (all from the same UCD release):
    UnicodeData.txt                canonical decompositions, combining classes
    DerivedNormalizationProps.txt  NFC_QC, Full_Composition_Exclusion
    NormalizationTest.txt          the conformance suite

Outputs, written next to this script:
    unicode_nfc_tables.inc            production tables, packed
    unicode_nfc_reference_tables.inc  test-only: the same tables unpacked
    unicode_nfc_test_vectors.inc      test-only conformance vectors
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

# The script's directory, and the repo root three directories above it.
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]

UNICODE_VERSION = "16.0.0"
UCD_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"
UCD_FILES = (
    "UnicodeData.txt",
    "DerivedNormalizationProps.txt",
    "NormalizationTest.txt",
)

# Precomposed Hangul syllable block (Unicode 3.12).
HANGUL_S_BASE = 0xAC00
HANGUL_L_COUNT = 19
HANGUL_V_COUNT = 21
HANGUL_T_COUNT = 28
HANGUL_S_COUNT = HANGUL_L_COUNT * HANGUL_V_COUNT * HANGUL_T_COUNT

BANNER = """// GENERATED by gen_unicode_tables.py from Unicode {version}. Do not edit.
//
// Included by unicode_nfc.cpp, which owns the algorithm; this file is data only.
""".format(version=UNICODE_VERSION)


def fetch(ucd_dir: Path, download: bool) -> dict[str, str]:
    ucd_dir.mkdir(parents=True, exist_ok=True)
    out = {}
    for name in UCD_FILES:
        path = ucd_dir / name
        if download and not path.exists():
            print(f"fetching {name}", file=sys.stderr)
            with urllib.request.urlopen(f"{UCD_URL}/{name}", timeout=60) as r:
                path.write_bytes(r.read())
        if not path.exists():
            raise SystemExit(f"{path} not found; pass --download or --ucd-dir")
        out[name] = path.read_text(encoding="utf-8")
    return out


def parse_unicode_data(text: str) -> tuple[dict[int, int], dict[int, list[int]]]:
    """-> (combining class by codepoint, canonical decomposition by codepoint).
    Skips compatibility mappings, which carry a <tag> prefix.
    """
    ccc: dict[int, int] = {}
    decomp: dict[int, list[int]] = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        f = line.split(";")
        cp = int(f[0], 16)
        if (klass := int(f[3])) != 0:
            ccc[cp] = klass
        mapping = f[5].strip()
        if mapping and not mapping.startswith("<"):
            decomp[cp] = [int(x, 16) for x in mapping.split()]
    return ccc, decomp


def parse_derived_props(text: str) -> tuple[set[int], set[int]]:
    """-> (codepoints where NFC_QC is not Yes, Full_Composition_Exclusion set)."""
    qc_not_yes: set[int] = set()
    excluded: set[int] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        rng = f[0].split("..")
        lo = int(rng[0], 16)
        hi = int(rng[-1], 16)
        if f[1] == "NFC_QC" and f[2] in ("N", "M"):
            qc_not_yes.update(range(lo, hi + 1))
        elif f[1] == "Full_Composition_Exclusion":
            excluded.update(range(lo, hi + 1))
    return qc_not_yes, excluded


def full_decompose(cp: int, decomp: dict[int, list[int]]) -> list[int]:
    """Full canonical decomposition of `cp`, expanded recursively."""
    if cp not in decomp:
        return [cp]
    out: list[int] = []
    for part in decomp[cp]:
        out.extend(full_decompose(part, decomp))
    return out


def to_ranges(codepoints: set[int]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for cp in sorted(codepoints):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def emit_array(name: str, ctype: str, values: list[str], per_line: int) -> str:
    """C++ source for a constexpr std::array `name`, `per_line` values per line."""
    if not values:
        # One placeholder element; the count constant bounds reads.
        return f"constexpr std::array<{ctype}, 1> {name}{{ 0 }};\n"
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("  " + " ".join(v + "," for v in values[i:i + per_line]))
    body = "\n".join(lines)
    return (f"constexpr std::array<{ctype}, {len(values)}> {name}{{\n"
            f"{body}\n}};\n")


def uvarint(out: bytearray, value: int) -> None:
    """LEB128: seven bits a byte, least significant first, high bit = more."""
    while value >= 0x80:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.append(value)


def zigzag(value: int) -> int:
    return (value << 1) if value >= 0 else ((-value << 1) - 1)


def build_packed(ccc: dict[int, int],
                 decomp: dict[int, list[int]],
                 qc_not_yes: set[int],
                 excluded: set[int]) -> str:
    """build_tables' arrays as one uvarint stream: unsafe ranges (gap, span), ccc runs
    (gap, span, class byte), decompositions (gap, length, zigzag deltas chained from
    the key), composites (starter delta, combining delta, zigzag from the starter)."""
    unsafe = to_ranges(set(qc_not_yes) | set(ccc))
    runs: list[list[int]] = []
    for cp in sorted(ccc):
        if runs and runs[-1][1] == cp - 1 and runs[-1][2] == ccc[cp]:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, ccc[cp]])
    decomp_keys = sorted(decomp)
    pairs = sorted((decomp[cp][0], decomp[cp][1], cp) for cp in decomp_keys
                   if len(decomp[cp]) == 2 and cp not in excluded)

    out = bytearray()
    prev = 0
    for lo, hi in unsafe:
        uvarint(out, lo - prev)
        uvarint(out, hi - lo)
        prev = hi + 1
    prev = 0
    for lo, hi, klass in runs:
        uvarint(out, lo - prev)
        uvarint(out, hi - lo)
        out.append(klass)
        prev = hi + 1
    prev = 0
    flat = 0
    for cp in decomp_keys:
        seq = full_decompose(cp, decomp)
        uvarint(out, cp - prev)
        uvarint(out, len(seq))
        ref = cp
        for part in seq:
            uvarint(out, zigzag(part - ref))
            ref = part
        prev = cp + 1
        flat += len(seq)
    starter = 0
    combining = 0
    for a, b, c in pairs:
        uvarint(out, a - starter)
        if a != starter:
            starter, combining = a, 0
        uvarint(out, b - combining)
        combining = b
        uvarint(out, zigzag(c - a))

    text = [BANNER, "\n"]
    text.append(f"constexpr uint32_t NFC_UNSAFE_COUNT{{ {len(unsafe)} }};\n")
    text.append(f"constexpr uint32_t NFC_CCC_RUNS{{ {len(runs)} }};\n")
    text.append(f"constexpr uint32_t NFC_CCC_COUNT{{ {len(ccc)} }};\n")
    text.append(f"constexpr uint32_t NFC_DECOMP_COUNT{{ {len(decomp_keys)} }};\n")
    text.append(f"constexpr uint32_t NFC_DECOMP_DATA_COUNT{{ {flat} }};\n")
    text.append(f"constexpr uint32_t NFC_COMPOSE_COUNT{{ {len(pairs)} }};\n\n")
    text.append("// See gen_unicode_tables.py's build_packed for the layout.\n")
    text.append(emit_array("NFC_PACKED", "scav_byte", [str(b) for b in out], 24))
    return "".join(text)


def build_tables(ccc: dict[int, int],
                 decomp: dict[int, list[int]],
                 qc_not_yes: set[int],
                 excluded: set[int]) -> str:
    # Already NFC when no codepoint reorders (ccc != 0) and none composes or
    # decomposes (NFC_QC != Yes). Hangul is NFC_QC=Yes and passes through.
    unsafe = set(qc_not_yes) | set(ccc)
    ranges = to_ranges(unsafe)

    ccc_keys = sorted(ccc)
    decomp_keys = sorted(decomp)

    flat: list[int] = []
    offsets: list[tuple[int, int]] = []
    for cp in decomp_keys:
        seq = full_decompose(cp, decomp)
        offsets.append((len(flat), len(seq)))
        flat.extend(seq)

    # Primary composites are the two-codepoint canonical mappings outside
    # Full_Composition_Exclusion, which already covers the other exclusions.
    pairs: list[tuple[int, int, int]] = []
    for cp in decomp_keys:
        seq = decomp[cp]
        if len(seq) == 2 and cp not in excluded:
            pairs.append((seq[0], seq[1], cp))
    pairs.sort()

    out = [BANNER.replace("unicode_nfc.cpp, which owns the algorithm; this file is data only",
                          "unicode_nfc_tests.cpp, against the decode of the packed tables"),
           "\n"]
    out.append("// Codepoints that may need work: NFC_QC != Yes, or a non-zero\n"
               "// combining class. Everything outside these ranges is already NFC.\n")
    out.append(emit_array("NFC_UNSAFE_LO", "uint32_t",
                          [f"0x{lo:X}" for lo, _ in ranges], 8))
    out.append(emit_array("NFC_UNSAFE_HI", "uint32_t",
                          [f"0x{hi:X}" for _, hi in ranges], 8))

    out.append("// Canonical combining class, for codepoints where it is non-zero.\n")
    out.append(emit_array("CCC_KEYS", "uint32_t",
                          [f"0x{cp:X}" for cp in ccc_keys], 8))
    out.append(emit_array("CCC_VALUES", "scav_byte",
                          [str(ccc[cp]) for cp in ccc_keys], 16))

    out.append("// Fully-expanded canonical decompositions, flattened.\n")
    out.append(emit_array("DECOMP_KEYS", "uint32_t",
                          [f"0x{cp:X}" for cp in decomp_keys], 8))
    out.append(emit_array("DECOMP_OFFSETS", "uint32_t",
                          [str(off) for off, _ in offsets], 12))
    out.append(emit_array("DECOMP_LENGTHS", "scav_byte",
                          [str(n) for _, n in offsets], 16))
    out.append(emit_array("DECOMP_DATA", "uint32_t",
                          [f"0x{cp:X}" for cp in flat], 8))

    out.append("// Primary composites, keyed by (starter << 32) | combining.\n")
    out.append(emit_array("COMPOSE_KEYS", "uint64_t",
                          [f"0x{(a << 32) | b:X}ULL" for a, b, _ in pairs], 4))
    out.append(emit_array("COMPOSE_VALUES", "uint32_t",
                          [f"0x{c:X}" for _, _, c in pairs], 8))
    return "".join(out)


# Part 1 keeps non-Hangul rows whose index in the part is a multiple of PART1_STRIDE.
# Other parts are kept whole.
PART1_STRIDE = 6
# Part 1 keeps every PART1_HANGUL_STRIDE-th Hangul row, covering every L, V and T index.
PART1_HANGUL_STRIDE = 41
HANGUL_RANGES = ((0x1100, 0x11FF), (0xA960, 0xA97F), (0xAC00, 0xD7FF))

MAX_SEQ_LEN = 0xFF  # both lengths are packed into one uint16


def is_hangul(codepoints: list[int]) -> bool:
    return any(lo <= cp <= hi for cp in codepoints for lo, hi in HANGUL_RANGES)


def build_vectors(text: str) -> str:
    """NFC cases per row `c1;c2;c3;c4;c5`: c1, c2, c3 map to c2; c4, c5 map to c4.
    `flat` holds each source then expected; expected length 0 means equal to source.
    """
    flat: list[int] = []
    lens: list[tuple[int, int]] = []
    kept: dict[int, int] = {}
    seen: set[tuple[tuple[int, ...], tuple[int, ...]]] = set()

    def add(part: int, source: list[int], expected: list[int]) -> None:
        if len(source) > MAX_SEQ_LEN or len(expected) > MAX_SEQ_LEN:
            raise SystemExit(f"sequence longer than {MAX_SEQ_LEN} does not pack")
        key = (tuple(source), tuple(expected))
        if key in seen:
            return
        seen.add(key)
        flat.extend(source)
        if source == expected:
            lens.append((len(source), 0))
        else:
            flat.extend(expected)
            lens.append((len(source), len(expected)))
        kept[part] = kept.get(part, 0) + 1

    part = -1
    row_in_part = 0
    hangul_row = 0
    for line in text.splitlines():
        if line.startswith("@Part"):
            part = int(line[5])
            row_in_part = 0
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cols = [c.strip() for c in line.split(";") if c.strip()]
        if len(cols) < 5:
            continue
        c = [[int(x, 16) for x in col.split()] for col in cols[:5]]
        row_in_part += 1
        if part == 1:
            if is_hangul(c[0]) or is_hangul(c[1]):
                hangul_row += 1
                if hangul_row % PART1_HANGUL_STRIDE != 0:
                    continue
            elif row_in_part % PART1_STRIDE != 0:
                continue
            add(part, c[0], c[1])
            add(part, c[2], c[1])
            continue
        for source in (c[0], c[1], c[2]):
            add(part, source, c[1])
        for source in (c[3], c[4]):
            add(part, source, c[3])

    tally = ", ".join(f"part{p}={n}" for p, n in sorted(kept.items()))
    out = [BANNER.replace("unicode_nfc.cpp, which owns the algorithm; this file "
                          "is data only",
                          "unicode_nfc_tests.cpp"), "\n"]
    out.append("// Unicode's NormalizationTest.txt, NFC columns only.\n")
    out.append(f"// Cases by suite part: {tally}.\n")
    out.append(emit_array("NFC_VECTOR_DATA", "uint32_t",
                          [f"0x{cp:X}" for cp in flat], 12))
    out.append("// Packed (source length << 8) | expected length, in order.\n")
    out.append(emit_array("NFC_VECTOR_LENS", "uint16_t",
                          [f"0x{(a << 8) | b:04X}" for a, b in lens], 12))
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ucd-dir", type=Path, default=REPO_ROOT / "out/ucd")
    ap.add_argument("--download", action="store_true")
    ap.add_argument("--out-dir", type=Path, default=HERE)
    args = ap.parse_args()

    ucd = fetch(args.ucd_dir, args.download)
    ccc, decomp = parse_unicode_data(ucd["UnicodeData.txt"])
    qc_not_yes, excluded = parse_derived_props(ucd["DerivedNormalizationProps.txt"])

    # Drops Hangul syllable decompositions; unicode_nfc.cpp computes them.
    for cp in range(HANGUL_S_BASE, HANGUL_S_BASE + HANGUL_S_COUNT):
        decomp.pop(cp, None)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    tables = args.out_dir / "unicode_nfc_tables.inc"
    reference = args.out_dir / "unicode_nfc_reference_tables.inc"
    vectors = args.out_dir / "unicode_nfc_test_vectors.inc"
    tables.write_text(build_packed(ccc, decomp, qc_not_yes, excluded),
                      encoding="utf-8", newline="\n")
    reference.write_text(build_tables(ccc, decomp, qc_not_yes, excluded),
                         encoding="utf-8", newline="\n")
    vectors.write_text(build_vectors(ucd["NormalizationTest.txt"]),
                       encoding="utf-8", newline="\n")
    for path in (tables, reference, vectors):
        print(f"wrote {path} ({path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
