#ifndef SCAV_CORE_LANG_UNICODE_NFC_H_INCLUDED
#define SCAV_CORE_LANG_UNICODE_NFC_H_INCLUDED

// NFC, over codepoints. PRD 6 normalizes text at parse because NFD on macOS and
// NFC everywhere else otherwise put different bytes in the string pool from the
// same commit, and the format hash follows the pool.
//
// Tables are generated by tools/gen_unicode_tables.py and committed, so a build
// needs neither the UCD nor Python. Hangul is algorithmic in both directions and
// therefore has no table entry at all.

#include <cstdint>
#include <vector>

namespace scav {

// True when `cp` is outside the quick-check-yes set: it either has a non-zero
// combining class or NFC_QC says it may compose or decompose. Text made only of
// codepoints this returns false for is already NFC.
bool nfc_needs_work(uint32_t cp);

uint32_t nfc_combining_class(uint32_t cp);

// `out` is cleared first. Returns true when the result differs from `in`.
bool nfc_normalize(std::vector<uint32_t> const &in, std::vector<uint32_t> &out);

}  // namespace scav

#endif  // SCAV_CORE_LANG_UNICODE_NFC_H_INCLUDED
