"""Generated by tools/gen_bindings.py from abi/scav_abi.json. Do not edit.

The low-level layer: one ctypes declaration per ABI entity, with every struct's
size and alignment asserted against what the C toolchain measured. An assertion
here failing means the loaded library is not the one this file was generated
from, which is a better failure than a silent misread.
"""

import ctypes
from pathlib import Path


class ScavError(RuntimeError):
    """A non-zero scav_result, carrying its code."""

    def __init__(self, code: int, call: str) -> None:
        super().__init__(f"{call} failed: {ERROR_NAMES.get(code, code)}")
        self.code = code
        self.call = call


def check(code: int, call: str) -> int:
    if code < 0:
        raise ScavError(code, call)
    return code


# Opaque handles. Distinct types on purpose: passing one where another
# belongs is a TypeError rather than a segfault.
class scav_load(ctypes.Structure):
    pass

class scav_chart(ctypes.Structure):
    pass

class scav_metrics(ctypes.Structure):
    pass

class scav_images(ctypes.Structure):
    pass

class scav_drawlist(ctypes.Structure):
    pass

SCAV_OK = 0
SCAV_E_INVALID_ARG = -1
SCAV_E_STATE = -2
SCAV_E_CAPACITY = -3
SCAV_E_LOAD = -4
SCAV_E_LAYOUT = -5
SCAV_E_FONT = -6
SCAV_E_NO_GLYPH = -7
SCAV_E_DRAWLIST = -8
SCAV_PRIM_RECT = 0
SCAV_PRIM_RRECT = 1
SCAV_PRIM_LINE = 2
SCAV_PRIM_POLYLINE = 3
SCAV_PRIM_PATH = 4
SCAV_PRIM_TEXT = 5
SCAV_PRIM_CIRCLE = 6
SCAV_PRIM_ARC = 7
SCAV_PRIM_IMAGE = 8
SCAV_PRIM_KIND_COUNT = 9
SCAV_STYLE_STATE = 0
SCAV_STYLE_SUB = 1
SCAV_STYLE_ROUTE = 2
SCAV_STYLE_TITLE = 3
SCAV_STYLE_LABEL = 4
SCAV_STYLE_PSEUDO = 5
SCAV_STYLE_COUNT = 6
SCAV_CLIP_NONE = 4294967295

ERROR_NAMES = {
    0: "SCAV_OK",
    -1: "SCAV_E_INVALID_ARG",
    -2: "SCAV_E_STATE",
    -3: "SCAV_E_CAPACITY",
    -4: "SCAV_E_LOAD",
    -5: "SCAV_E_LAYOUT",
    -6: "SCAV_E_FONT",
    -7: "SCAV_E_NO_GLYPH",
    -8: "SCAV_E_DRAWLIST",
}

scav_byte = ctypes.c_ubyte
scav_result = ctypes.c_int32
scav_column_id = ctypes.c_uint32
scav_router_id = ctypes.c_uint32

class scav_span(ctypes.Structure):
    _fields_ = [
        ("off", ctypes.c_uint32),
        ("len", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_span) == 8, "scav_span is not 8 bytes"
assert ctypes.alignment(scav_span) == 4
assert getattr(scav_span, "off").offset == 0
assert getattr(scav_span, "len").offset == 4

class scav_point(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_int32),
        ("y", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_point) == 8, "scav_point is not 8 bytes"
assert ctypes.alignment(scav_point) == 4
assert getattr(scav_point, "x").offset == 0
assert getattr(scav_point, "y").offset == 4

class scav_extent(ctypes.Structure):
    _fields_ = [
        ("w", ctypes.c_int32),
        ("h", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_extent) == 8, "scav_extent is not 8 bytes"
assert ctypes.alignment(scav_extent) == 4
assert getattr(scav_extent, "w").offset == 0
assert getattr(scav_extent, "h").offset == 4

class scav_rect(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_int32),
        ("y", ctypes.c_int32),
        ("w", ctypes.c_int32),
        ("h", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_rect) == 16, "scav_rect is not 16 bytes"
assert ctypes.alignment(scav_rect) == 4
assert getattr(scav_rect, "x").offset == 0
assert getattr(scav_rect, "y").offset == 4
assert getattr(scav_rect, "w").offset == 8
assert getattr(scav_rect, "h").offset == 12

class scav_pending(ctypes.Structure):
    _fields_ = [
        ("path", scav_span),
        ("from_doc", ctypes.c_uint32),
        ("stmt_row", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_pending) == 16, "scav_pending is not 16 bytes"
assert ctypes.alignment(scav_pending) == 4
assert getattr(scav_pending, "path").offset == 0
assert getattr(scav_pending, "from_doc").offset == 8
assert getattr(scav_pending, "stmt_row").offset == 12

class scav_diag(ctypes.Structure):
    _fields_ = [
        ("code", ctypes.c_uint32),
        ("subject_kind", ctypes.c_uint32),
        ("subject_ordinal", ctypes.c_uint32),
        ("doc", ctypes.c_uint32),
        ("off", ctypes.c_uint32),
        ("len", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_diag) == 24, "scav_diag is not 24 bytes"
assert ctypes.alignment(scav_diag) == 4
assert getattr(scav_diag, "code").offset == 0
assert getattr(scav_diag, "subject_kind").offset == 4
assert getattr(scav_diag, "subject_ordinal").offset == 8
assert getattr(scav_diag, "doc").offset == 12
assert getattr(scav_diag, "off").offset == 16
assert getattr(scav_diag, "len").offset == 20

class scav_box_space(ctypes.Structure):
    _fields_ = [
        ("min_w", ctypes.c_int32),
        ("h_before", ctypes.c_int32),
        ("h_after", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_box_space) == 12, "scav_box_space is not 12 bytes"
assert ctypes.alignment(scav_box_space) == 4
assert getattr(scav_box_space, "min_w").offset == 0
assert getattr(scav_box_space, "h_before").offset == 4
assert getattr(scav_box_space, "h_after").offset == 8

class scav_path_clear(ctypes.Structure):
    _fields_ = [
        ("src", ctypes.c_int32),
        ("dst", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_path_clear) == 8, "scav_path_clear is not 8 bytes"
assert ctypes.alignment(scav_path_clear) == 4
assert getattr(scav_path_clear, "src").offset == 0
assert getattr(scav_path_clear, "dst").offset == 4

class scav_path_box(ctypes.Structure):
    _fields_ = [
        ("subject", ctypes.c_uint32),
        ("w", ctypes.c_int32),
        ("h", ctypes.c_int32),
        ("order", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_path_box) == 16, "scav_path_box is not 16 bytes"
assert ctypes.alignment(scav_path_box) == 4
assert getattr(scav_path_box, "subject").offset == 0
assert getattr(scav_path_box, "w").offset == 4
assert getattr(scav_path_box, "h").offset == 8
assert getattr(scav_path_box, "order").offset == 12

class scav_spaces(ctypes.Structure):
    _fields_ = [
        ("box_state", ctypes.POINTER(scav_box_space)),
        ("n_box_state", ctypes.c_uint32),
        ("box_sub", ctypes.POINTER(scav_box_space)),
        ("n_box_sub", ctypes.c_uint32),
        ("path_clear", ctypes.POINTER(scav_path_clear)),
        ("n_path_clear", ctypes.c_uint32),
        ("path_box", ctypes.POINTER(scav_path_box)),
        ("n_path_box", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_spaces) == 64, "scav_spaces is not 64 bytes"
assert ctypes.alignment(scav_spaces) == 8
assert getattr(scav_spaces, "box_state").offset == 0
assert getattr(scav_spaces, "n_box_state").offset == 8
assert getattr(scav_spaces, "box_sub").offset == 16
assert getattr(scav_spaces, "n_box_sub").offset == 24
assert getattr(scav_spaces, "path_clear").offset == 32
assert getattr(scav_spaces, "n_path_clear").offset == 40
assert getattr(scav_spaces, "path_box").offset == 48
assert getattr(scav_spaces, "n_path_box").offset == 56

class scav_profile(ctypes.Structure):
    _fields_ = [
        ("profile_id", ctypes.c_int32),
        ("profile_version", ctypes.c_int32),
        ("pad", ctypes.c_int32),
        ("font_size_grid", ctypes.c_int32),
        ("line_height_k_num", ctypes.c_int32),
        ("line_height_k_den", ctypes.c_int32),
        ("kind_min_w", ctypes.c_int32 * 9),
        ("kind_min_h", ctypes.c_int32 * 9),
        ("dar_num", ctypes.c_int32),
        ("dar_den", ctypes.c_int32),
        ("trybox", ctypes.c_int32),
        ("sm_tiebreak", ctypes.c_int32),
        ("w_bends", ctypes.c_int32),
        ("w_corridor", ctypes.c_int32),
        ("w_crossings", ctypes.c_int32),
        ("w_excess_len", ctypes.c_int32),
        ("w_adjacency", ctypes.c_int32),
        ("w_label", ctypes.c_int32),
        ("w_aspect", ctypes.c_int32),
        ("w_area", ctypes.c_int32),
        ("portfolio_k", ctypes.c_int32),
        ("sweep_count", ctypes.c_int32),
        ("congestion_iterations", ctypes.c_int32),
        ("ripup_cap", ctypes.c_int32),
        ("spacing_inflation_cap", ctypes.c_int32),
        ("spacing_inflation_increment", ctypes.c_int32),
        ("print_columns", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_profile) == 172, "scav_profile is not 172 bytes"
assert ctypes.alignment(scav_profile) == 4
assert getattr(scav_profile, "profile_id").offset == 0
assert getattr(scav_profile, "profile_version").offset == 4
assert getattr(scav_profile, "pad").offset == 8
assert getattr(scav_profile, "font_size_grid").offset == 12
assert getattr(scav_profile, "line_height_k_num").offset == 16
assert getattr(scav_profile, "line_height_k_den").offset == 20
assert getattr(scav_profile, "kind_min_w").offset == 24
assert getattr(scav_profile, "kind_min_h").offset == 60
assert getattr(scav_profile, "dar_num").offset == 96
assert getattr(scav_profile, "dar_den").offset == 100
assert getattr(scav_profile, "trybox").offset == 104
assert getattr(scav_profile, "sm_tiebreak").offset == 108
assert getattr(scav_profile, "w_bends").offset == 112
assert getattr(scav_profile, "w_corridor").offset == 116
assert getattr(scav_profile, "w_crossings").offset == 120
assert getattr(scav_profile, "w_excess_len").offset == 124
assert getattr(scav_profile, "w_adjacency").offset == 128
assert getattr(scav_profile, "w_label").offset == 132
assert getattr(scav_profile, "w_aspect").offset == 136
assert getattr(scav_profile, "w_area").offset == 140
assert getattr(scav_profile, "portfolio_k").offset == 144
assert getattr(scav_profile, "sweep_count").offset == 148
assert getattr(scav_profile, "congestion_iterations").offset == 152
assert getattr(scav_profile, "ripup_cap").offset == 156
assert getattr(scav_profile, "spacing_inflation_cap").offset == 160
assert getattr(scav_profile, "spacing_inflation_increment").offset == 164
assert getattr(scav_profile, "print_columns").offset == 168

class scav_port_slot(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_int32),
        ("y", ctypes.c_int32),
        ("side", ctypes.c_uint32),
        ("boundary_depth", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_port_slot) == 16, "scav_port_slot is not 16 bytes"
assert ctypes.alignment(scav_port_slot) == 4
assert getattr(scav_port_slot, "x").offset == 0
assert getattr(scav_port_slot, "y").offset == 4
assert getattr(scav_port_slot, "side").offset == 8
assert getattr(scav_port_slot, "boundary_depth").offset == 12

class scav_layout_opts(ctypes.Structure):
    _fields_ = [
        ("profile", scav_profile),
        ("router", scav_router_id),
        ("threads", ctypes.c_uint32),
    ]

assert ctypes.sizeof(scav_layout_opts) == 180, "scav_layout_opts is not 180 bytes"
assert ctypes.alignment(scav_layout_opts) == 4
assert getattr(scav_layout_opts, "profile").offset == 0
assert getattr(scav_layout_opts, "router").offset == 172
assert getattr(scav_layout_opts, "threads").offset == 176

class scav_style(ctypes.Structure):
    _fields_ = [
        ("stroke_rgba", ctypes.c_uint32),
        ("fill_rgba", ctypes.c_uint32),
        ("stroke_w", ctypes.c_int32),
        ("dash", ctypes.c_uint32),
        ("font_size_grid", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_style) == 20, "scav_style is not 20 bytes"
assert ctypes.alignment(scav_style) == 4
assert getattr(scav_style, "stroke_rgba").offset == 0
assert getattr(scav_style, "fill_rgba").offset == 4
assert getattr(scav_style, "stroke_w").offset == 8
assert getattr(scav_style, "dash").offset == 12
assert getattr(scav_style, "font_size_grid").offset == 16

class scav_prim(ctypes.Structure):
    _fields_ = [
        ("kind", ctypes.c_uint32),
        ("depth", ctypes.c_int32),
        ("style", ctypes.c_uint32),
        ("clip", ctypes.c_uint32),
        ("origin_kind", ctypes.c_uint32),
        ("origin_ordinal", ctypes.c_uint32),
        ("points", scav_span),
        ("payload", scav_span),
        ("a", ctypes.c_int32),
        ("b", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_prim) == 48, "scav_prim is not 48 bytes"
assert ctypes.alignment(scav_prim) == 4
assert getattr(scav_prim, "kind").offset == 0
assert getattr(scav_prim, "depth").offset == 4
assert getattr(scav_prim, "style").offset == 8
assert getattr(scav_prim, "clip").offset == 12
assert getattr(scav_prim, "origin_kind").offset == 16
assert getattr(scav_prim, "origin_ordinal").offset == 20
assert getattr(scav_prim, "points").offset == 24
assert getattr(scav_prim, "payload").offset == 32
assert getattr(scav_prim, "a").offset == 40
assert getattr(scav_prim, "b").offset == 44

class scav_svg_options(ctypes.Structure):
    _fields_ = [
        ("embed_font", ctypes.c_int32),
        ("margin", ctypes.c_int32),
    ]

assert ctypes.sizeof(scav_svg_options) == 8, "scav_svg_options is not 8 bytes"
assert ctypes.alignment(scav_svg_options) == 4
assert getattr(scav_svg_options, "embed_font").offset == 0
assert getattr(scav_svg_options, "margin").offset == 4

scav_placed = scav_rect

def _bind(lib: ctypes.CDLL) -> None:
    lib.scav_abi_version.argtypes = []
    lib.scav_abi_version.restype = ctypes.c_uint32
    lib.scav_load_begin.argtypes = [ctypes.POINTER(ctypes.POINTER(scav_load))]
    lib.scav_load_begin.restype = scav_result
    lib.scav_load_add.argtypes = [ctypes.POINTER(scav_load), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.c_char_p]
    lib.scav_load_add.restype = scav_result
    lib.scav_load_pending.argtypes = [ctypes.POINTER(scav_load), ctypes.POINTER(ctypes.POINTER(scav_pending)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_load_pending.restype = scav_result
    lib.scav_load_path.argtypes = [ctypes.POINTER(scav_load), scav_span, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_load_path.restype = scav_result
    lib.scav_load_finish.argtypes = [ctypes.POINTER(scav_load), ctypes.POINTER(ctypes.POINTER(scav_chart))]
    lib.scav_load_finish.restype = scav_result
    lib.scav_load_destroy.argtypes = [ctypes.POINTER(scav_load)]
    lib.scav_load_destroy.restype = None
    lib.scav_chart_destroy.argtypes = [ctypes.POINTER(scav_chart)]
    lib.scav_chart_destroy.restype = None
    lib.scav_load_diag_count.argtypes = [ctypes.POINTER(scav_load), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_load_diag_count.restype = scav_result
    lib.scav_load_diag.argtypes = [ctypes.POINTER(scav_load), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_load_diag.restype = scav_result
    lib.scav_diag_message.argtypes = [ctypes.c_uint32]
    lib.scav_diag_message.restype = ctypes.c_char_p
    lib.scav_load_document_name.argtypes = [ctypes.POINTER(scav_load), ctypes.c_uint32, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_load_document_name.restype = scav_result
    lib.scav_chart_counts.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_chart_counts.restype = scav_result
    lib.scav_chart_structural_hash.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_chart_structural_hash.restype = scav_result
    lib.scav_chart_digest.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_chart_digest.restype = scav_result
    lib.scav_chart_diag_count.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_chart_diag_count.restype = scav_result
    lib.scav_chart_diag.argtypes = [ctypes.POINTER(scav_chart), ctypes.c_uint32, ctypes.POINTER(scav_diag)]
    lib.scav_chart_diag.restype = scav_result
    lib.scav_column_find.argtypes = [ctypes.POINTER(scav_chart), ctypes.c_char_p, ctypes.POINTER(scav_column_id)]
    lib.scav_column_find.restype = scav_result
    lib.scav_column_data.argtypes = [ctypes.POINTER(scav_chart), scav_column_id, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_column_data.restype = scav_result
    lib.scav_column_count.argtypes = [ctypes.POINTER(scav_chart), scav_column_id, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_column_count.restype = scav_result
    lib.scav_str.argtypes = [ctypes.POINTER(scav_chart), scav_span, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_str.restype = scav_result
    lib.scav_profile_named.argtypes = [ctypes.c_char_p, ctypes.POINTER(scav_profile)]
    lib.scav_profile_named.restype = scav_result
    lib.scav_profile_validate.argtypes = [ctypes.POINTER(scav_profile)]
    lib.scav_profile_validate.restype = scav_result
    lib.scav_layout_run.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(scav_spaces), ctypes.POINTER(scav_layout_opts), ctypes.POINTER(scav_placed), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_layout_run.restype = scav_result
    lib.scav_router_list.argtypes = [ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_router_list.restype = scav_result
    lib.scav_router_name.argtypes = [ctypes.c_uint32, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_router_name.restype = scav_result
    lib.scav_router_by_name.argtypes = [ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.POINTER(scav_router_id)]
    lib.scav_router_by_name.restype = scav_result
    lib.scav_metrics_create.argtypes = [ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.POINTER(ctypes.POINTER(scav_metrics))]
    lib.scav_metrics_create.restype = scav_result
    lib.scav_metrics_destroy.argtypes = [ctypes.POINTER(scav_metrics)]
    lib.scav_metrics_destroy.restype = None
    lib.scav_metrics_identity.argtypes = [ctypes.POINTER(scav_metrics), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_metrics_identity.restype = scav_result
    lib.scav_metrics_units_per_em.argtypes = [ctypes.POINTER(scav_metrics), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_metrics_units_per_em.restype = scav_result
    lib.scav_metrics_glyph_count.argtypes = [ctypes.POINTER(scav_metrics), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_metrics_glyph_count.restype = scav_result
    lib.scav_measure_text.argtypes = [ctypes.POINTER(scav_metrics), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.c_int32, ctypes.POINTER(scav_extent)]
    lib.scav_measure_text.restype = scav_result
    lib.scav_line_height.argtypes = [ctypes.c_int32, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32)]
    lib.scav_line_height.restype = scav_result
    lib.scav_measure_block.argtypes = [ctypes.POINTER(scav_metrics), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.c_int32, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(scav_extent)]
    lib.scav_measure_block.restype = scav_result
    lib.scav_drawlist_create.argtypes = [ctypes.POINTER(ctypes.POINTER(scav_drawlist))]
    lib.scav_drawlist_create.restype = scav_result
    lib.scav_drawlist_destroy.argtypes = [ctypes.POINTER(scav_drawlist)]
    lib.scav_drawlist_destroy.restype = None
    lib.scav_drawlist_counts.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_counts.restype = scav_result
    lib.scav_drawlist_prims.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.POINTER(scav_prim)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_prims.restype = scav_result
    lib.scav_drawlist_styles.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.POINTER(scav_style)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_styles.restype = scav_result
    lib.scav_drawlist_points.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.POINTER(scav_point)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_points.restype = scav_result
    lib.scav_drawlist_clips.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.POINTER(scav_rect)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_clips.restype = scav_result
    lib.scav_drawlist_str.argtypes = [ctypes.POINTER(scav_drawlist), scav_span, ctypes.POINTER(ctypes.POINTER(scav_byte)), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_str.restype = scav_result
    lib.scav_drawlist_validate.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_validate.restype = scav_result
    lib.scav_drawlist_canonicalize.argtypes = [ctypes.POINTER(scav_drawlist)]
    lib.scav_drawlist_canonicalize.restype = scav_result
    lib.scav_drawlist_digest.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(scav_metrics), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_drawlist_digest.restype = scav_result
    lib.scav_drawlist_append.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(scav_drawlist)]
    lib.scav_drawlist_append.restype = scav_result
    lib.scav_images_create.argtypes = [ctypes.POINTER(ctypes.POINTER(scav_images))]
    lib.scav_images_create.restype = scav_result
    lib.scav_images_destroy.argtypes = [ctypes.POINTER(scav_images)]
    lib.scav_images_destroy.restype = None
    lib.scav_image_register.argtypes = [ctypes.POINTER(scav_images), ctypes.c_char_p, ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.c_int32, ctypes.c_int32, ctypes.c_char_p]
    lib.scav_image_register.restype = scav_result
    lib.scav_image_count.argtypes = [ctypes.POINTER(scav_images), ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_image_count.restype = scav_result
    lib.scav_image_find.argtypes = [ctypes.POINTER(scav_images), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_image_find.restype = scav_result
    lib.scav_image_extent.argtypes = [ctypes.POINTER(scav_images), ctypes.c_uint32, ctypes.POINTER(scav_extent)]
    lib.scav_image_extent.restype = scav_result
    lib.scav_emit_chart.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(scav_chart), ctypes.POINTER(scav_metrics), ctypes.POINTER(scav_style), ctypes.c_uint32, ctypes.POINTER(scav_spaces), ctypes.POINTER(scav_placed), ctypes.c_uint32, ctypes.c_int32]
    lib.scav_emit_chart.restype = scav_result
    lib.scav_measure_chart.argtypes = [ctypes.POINTER(scav_chart), ctypes.POINTER(scav_metrics), ctypes.POINTER(scav_profile), ctypes.POINTER(scav_box_space), ctypes.c_uint32, ctypes.POINTER(scav_box_space), ctypes.c_uint32, ctypes.POINTER(scav_path_clear), ctypes.c_uint32, ctypes.POINTER(scav_path_box), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_measure_chart.restype = scav_result
    lib.scav_palette_standard.argtypes = [ctypes.POINTER(scav_style), ctypes.c_uint32]
    lib.scav_palette_standard.restype = scav_result
    lib.scav_svg_write.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(scav_metrics), ctypes.POINTER(scav_images), ctypes.POINTER(scav_svg_options), ctypes.POINTER(scav_byte), ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
    lib.scav_svg_write.restype = scav_result
    lib.scav_svg_bounds.argtypes = [ctypes.POINTER(scav_drawlist), ctypes.POINTER(scav_rect)]
    lib.scav_svg_bounds.restype = scav_result


def load(library: str | Path | None = None) -> ctypes.CDLL:
    """Bind every entry point on a freshly loaded library.

    One redistributable shared object, so there is one thing to find. Passing a
    path is for a build tree; a wheel ships the library beside this file.
    """
    if library is None:
        here = Path(__file__).resolve().parent
        for name in ("libscav.dylib", "libscav.so", "scav.dll"):
            if (here / name).is_file():
                library = here / name
                break
        else:
            raise FileNotFoundError(f"no scav shared library beside {here}")
    lib = ctypes.CDLL(str(library))
    _bind(lib)
    return lib


__all__ = [
    "load", "check", "ScavError", "ERROR_NAMES",
    "scav_box_space",
    "scav_chart",
    "scav_diag",
    "scav_drawlist",
    "scav_extent",
    "scav_images",
    "scav_layout_opts",
    "scav_load",
    "scav_metrics",
    "scav_path_box",
    "scav_path_clear",
    "scav_pending",
    "scav_point",
    "scav_port_slot",
    "scav_prim",
    "scav_profile",
    "scav_rect",
    "scav_spaces",
    "scav_span",
    "scav_style",
    "scav_svg_options",
    "SCAV_OK",
    "SCAV_E_INVALID_ARG",
    "SCAV_E_STATE",
    "SCAV_E_CAPACITY",
    "SCAV_E_LOAD",
    "SCAV_E_LAYOUT",
    "SCAV_E_FONT",
    "SCAV_E_NO_GLYPH",
    "SCAV_E_DRAWLIST",
    "SCAV_PRIM_RECT",
    "SCAV_PRIM_RRECT",
    "SCAV_PRIM_LINE",
    "SCAV_PRIM_POLYLINE",
    "SCAV_PRIM_PATH",
    "SCAV_PRIM_TEXT",
    "SCAV_PRIM_CIRCLE",
    "SCAV_PRIM_ARC",
    "SCAV_PRIM_IMAGE",
    "SCAV_PRIM_KIND_COUNT",
    "SCAV_STYLE_STATE",
    "SCAV_STYLE_SUB",
    "SCAV_STYLE_ROUTE",
    "SCAV_STYLE_TITLE",
    "SCAV_STYLE_LABEL",
    "SCAV_STYLE_PSEUDO",
    "SCAV_STYLE_COUNT",
    "SCAV_CLIP_NONE",
]
