#!/usr/bin/env python3
"""Generate the low-level Python layer from the ABI JSON.

Bindings are generated, not hand-written, so the half that would drift cannot.
The idiomatic wrapper beside the output is the hand-written half and stays
small: everything here is pure marshalling, which is what having no callback
anywhere in the extension surface buys.

  tools/gen_bindings.py --abi abi/scav_abi.json --out bindings/python/scav/_abi.py
"""

import argparse
import json
import sys
from pathlib import Path

# Every fixed-width type the ABI uses, and nothing else: a type absent here is
# an error, because guessing a width is how a binding starts corrupting memory.
CTYPES = {
    "void": None,
    "char": "ctypes.c_char",
    "unsigned char": "ctypes.c_ubyte",
    "int8_t": "ctypes.c_int8",
    "int16_t": "ctypes.c_int16",
    "int32_t": "ctypes.c_int32",
    "int64_t": "ctypes.c_int64",
    "uint8_t": "ctypes.c_uint8",
    "uint16_t": "ctypes.c_uint16",
    "uint32_t": "ctypes.c_uint32",
    "uint64_t": "ctypes.c_uint64",
}

HEADER = '''"""Generated by tools/gen_bindings.py from abi/scav_abi.json. Do not edit.

The low-level layer: one ctypes declaration per ABI entity, with every struct's
size and alignment asserted against what the C toolchain measured. An assertion
here failing means the loaded library is not the one this file was generated
from, which is a better failure than a silent misread.
"""

import ctypes
from pathlib import Path


class ScavError(RuntimeError):
    """A non-zero scav_result, carrying its code."""

    def __init__(self, code: int, call: str) -> None:
        super().__init__(f"{call} failed: {ERROR_NAMES.get(code, code)}")
        self.code = code
        self.call = call


def check(code: int, call: str) -> int:
    if code < 0:
        raise ScavError(code, call)
    return code

'''

LOADER = '''

def load(library: str | Path | None = None) -> ctypes.CDLL:
    """Bind every entry point on a freshly loaded library.

    One redistributable shared object, so there is one thing to find. Passing a
    path is for a build tree; a wheel ships the library beside this file.
    """
    if library is None:
        here = Path(__file__).resolve().parent
        for name in ("libscav.dylib", "libscav.so", "scav.dll"):
            if (here / name).is_file():
                library = here / name
                break
        else:
            raise FileNotFoundError(f"no scav shared library beside {here}")
    lib = ctypes.CDLL(str(library))
    _bind(lib)
    return lib
'''


def ctype_of(type_info: dict, arrays: int | None = None) -> str:
    """A ctypes spelling for one ABI type."""
    name = type_info["name"]
    pointer = type_info["pointer"]
    if name in CTYPES:
        base = CTYPES[name]
        if base is None:
            if pointer == 0:
                return "None"
            # `void*` never appears in this ABI by design, so it is not modelled.
            raise SystemExit(f"gen_bindings: void with {pointer} pointers")
        # A `char*` is a NUL-terminated input name, which ctypes marshals from
        # bytes directly; anything wider stays an explicit pointer.
        if (name == "char") and (pointer == 1) and type_info["const"]:
            return "ctypes.c_char_p"
    else:
        base = name
    spelled = base
    for _ in range(pointer):
        spelled = f"ctypes.POINTER({spelled})"
    if arrays is not None:
        spelled = f"{spelled} * {arrays}"
    return spelled


def struct_class(struct: dict) -> str:
    lines = [f"class {struct['name']}(ctypes.Structure):",
             f"    _fields_ = ["]
    for field in struct["fields"]:
        lines.append(f'        ("{field["name"]}", '
                     f'{ctype_of(field["type"], field.get("array"))}),')
    lines.append("    ]")
    lines.append("")
    # The layout the C toolchain measured, asserted rather than assumed. Padding
    # is pinned, so a mismatch is an ABI break and not a portability quirk.
    lines.append(f"assert ctypes.sizeof({struct['name']}) == {struct['size']}, "
                 f'"{struct["name"]} is not {struct["size"]} bytes"')
    lines.append(f"assert ctypes.alignment({struct['name']}) == {struct['align']}")
    for field in struct["fields"]:
        # getattr, not attribute syntax: a C-legal field name can be a keyword
        # in the binding language, and the assertion must survive that.
        lines.append(f'assert getattr({struct["name"]}, "{field["name"]}").offset'
                     f' == {field["offset"]}')
    return "\n".join(lines)


def function_binding(fn: dict) -> str:
    args = ", ".join(ctype_of(p["type"]) for p in fn["params"])
    restype = ctype_of(fn["returns"])
    return (f'    lib.{fn["name"]}.argtypes = [{args}]\n'
            f'    lib.{fn["name"]}.restype = {restype}')


def generate(abi: dict) -> str:
    out = [HEADER]

    # Handles are opaque, so each is its own incomplete Structure: distinct
    # types, so a binding cannot hand a chart where a drawlist was wanted.
    handles = [h["name"] for header in abi["headers"] for h in header["handles"]]
    out.append("# Opaque handles. Distinct types on purpose: passing one where "
               "another\n# belongs is a TypeError rather than a segfault.")
    for name in handles:
        out.append(f"class {name}(ctypes.Structure):\n    pass\n")

    errors: dict[str, int] = {}
    constants: list[str] = []
    for header in abi["headers"]:
        for enum in header["enums"]:
            for value in enum["values"]:
                constants.append(f'{value["name"]} = {value["value"]}')
                if value["name"].startswith("SCAV_E_") or value["name"] == "SCAV_OK":
                    errors[value["name"]] = value["value"]
    for header in abi["headers"]:
        for constant in header.get("constants", []):
            constants.append(f'{constant["name"]} = {constant["value"]}')
    out.append("\n".join(constants) + "\n")
    out.append("ERROR_NAMES = {\n"
               + "".join(f'    {v}: "{k}",\n' for k, v in errors.items())
               + "}\n")

    # Aliases before the structs that use them, and structs in header order:
    # ctypes needs a name defined before it is referenced.
    aliases: list[str] = []
    for header in abi["headers"]:
        for alias in header["aliases"]:
            aliases.append(f'{alias["name"]} = {ctype_of(alias["target"])}')
    structs: list[str] = []
    for header in abi["headers"]:
        for struct in header["structs"]:
            structs.append(struct_class(struct))
    # An alias may name a struct, so the struct has to come first; and a struct
    # may name an alias. The ABI only aliases primitives and whole structs, so
    # two passes settle it: primitive aliases, structs, then the rest.
    primitive_aliases = [a for a in aliases if "ctypes." in a]
    struct_aliases = [a for a in aliases if "ctypes." not in a]
    out.append("\n".join(primitive_aliases) + "\n")
    out.append("\n\n".join(structs) + "\n")
    out.append("\n".join(struct_aliases) + "\n")

    out.append("def _bind(lib: ctypes.CDLL) -> None:")
    for header in abi["headers"]:
        for fn in header["functions"]:
            out.append(function_binding(fn))
    out.append(LOADER)

    names = handles + [s["name"] for h in abi["headers"] for s in h["structs"]]
    out.append('\n__all__ = [\n'
               + '    "load", "check", "ScavError", "ERROR_NAMES",\n'
               + "".join(f'    "{n}",\n' for n in sorted(set(names)))
               + "".join(f'    "{c.split(" = ")[0]}",\n' for c in constants)
               + "]\n")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--abi", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    abi = json.loads(args.abi.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generate(abi), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
