# Script mode: gzip SCAV_GZIP_INPUT, named relative to the working directory.
if(CMAKE_SCRIPT_MODE_FILE)
  file(ARCHIVE_CREATE OUTPUT "${SCAV_GZIP_OUTPUT}" PATHS "${SCAV_GZIP_INPUT}"
    FORMAT raw COMPRESSION GZip COMPRESSION_LEVEL 9)
  return()
endif()

include_guard(GLOBAL)

# scav_embed_bytes(<file> <symbol> <out_var> [GZIP]) -- a binary file as a C++
# source defining `scav::<SYMBOL>` and `<symbol>_len`, written into the build tree
# and returned in <out_var>. GZIP embeds a gzip member with a zero MTIME instead.
#
# CMake rather than a script: a build must not need Python, and `file(READ HEX)`
# plus one regex converts the bundled font in a sixth of a second. Configure
# time, so the generated source is a plain input to the compile.
function(scav_embed_bytes source symbol out_var)
  cmake_parse_arguments(PARSE_ARGV 3 arg "GZIP" "" "")
  cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    NORMALIZE OUTPUT_VARIABLE absolute)
  if(NOT EXISTS "${absolute}")
    message(FATAL_ERROR "scav_embed_bytes: no such file: ${absolute}")
  endif()

  # Read at configure time, so a later edit to the file has to re-run configure
  # or the executable would keep the bytes from the last one.
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${absolute}")

  set(form "")
  set(read "${absolute}")
  if(arg_GZIP)
    set(read "${CMAKE_CURRENT_BINARY_DIR}/scav_embed_${symbol}.gz")
    set(form ", gzipped")
    cmake_path(GET absolute PARENT_PATH directory)
    cmake_path(GET absolute FILENAME name)
    # In the input's own directory, so the path it is handed is a bare name.
    execute_process(
      COMMAND "${CMAKE_COMMAND}" "-DSCAV_GZIP_INPUT=${name}" "-DSCAV_GZIP_OUTPUT=${read}"
              -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
      WORKING_DIRECTORY "${directory}"
      RESULT_VARIABLE status)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "scav_embed_bytes: could not gzip ${absolute}")
    endif()
  endif()

  string(TOUPPER "${symbol}" upper)
  file(READ "${read}" hex HEX)
  if(arg_GZIP)
    # MTIME is bytes 4..7, zeroed so the output depends on the input alone.
    string(SUBSTRING "${hex}" 0 8 magic)
    if(NOT magic STREQUAL "1f8b0800")
      message(FATAL_ERROR "scav_embed_bytes: unexpected gzip header ${magic}")
    endif()
    string(SUBSTRING "${hex}" 16 -1 rest)
    set(hex "${magic}00000000${rest}")
  endif()
  string(LENGTH "${hex}" hex_length)
  math(EXPR byte_count "${hex_length} / 2")
  if(byte_count EQUAL 0)
    message(FATAL_ERROR "scav_embed_bytes: ${absolute} is empty")
  endif()

  # Two passes, and the order matters: convert every byte first, then break
  # lines on whole entries only. A second pass over raw hex pairs would match
  # inside the `0x..,` the first pass just wrote.
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n  "
    body "${body}")

  set(header "${CMAKE_CURRENT_BINARY_DIR}/scav_embed_${symbol}.h")
  file(CONFIGURE OUTPUT "${header}" CONTENT
"// Generated by scav_embed_bytes from ${absolute}${form}. Do not edit.
#ifndef SCAV_EMBED_${upper}_H_INCLUDED
#define SCAV_EMBED_${upper}_H_INCLUDED

#include \"scav/scav_types.h\"

#include <cstdint>

namespace scav {
scav_byte const *${symbol}_bytes(uint32_t &len);
}

#endif
" @ONLY NEWLINE_STYLE LF)

  set(generated "${CMAKE_CURRENT_BINARY_DIR}/scav_embed_${symbol}.cpp")
  # An accessor rather than an extern array, so no other translation unit needs
  # the byte count or a linter exemption to name the blob.
  file(CONFIGURE OUTPUT "${generated}" CONTENT
"// Generated by scav_embed_bytes from ${absolute}${form}. Do not edit.

#include \"scav_embed_${symbol}.h\"

#include <array>

namespace scav {

namespace {

std::array<scav_byte, ${byte_count}> const ${upper}{ {
  ${body}
} };

}  // namespace

scav_byte const *${symbol}_bytes(uint32_t &len) {
  len = ${byte_count}U;
  return ${upper}.data();
}

}  // namespace scav
" @ONLY NEWLINE_STYLE LF)

  # Generated code is not ours to lint or to hold to the warning set.
  set_source_files_properties("${generated}" PROPERTIES
    SKIP_LINTING ON
    COMPILE_OPTIONS ""
  )
  set(${out_var} "${generated}" PARENT_SCOPE)
endfunction()
