include_guard(GLOBAL)

# scav_embed_bytes(<file> <symbol> <out_var>) -- a binary file as a C++ source
# defining `scav::<SYMBOL>` and `<symbol>_len`, written into the build tree and
# returned in <out_var>.
#
# CMake rather than a script: a build must not need Python, and `file(READ HEX)`
# plus one regex converts the bundled font in a sixth of a second. Configure
# time, so the generated source is a plain input to the compile.
function(scav_embed_bytes source symbol out_var)
  cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    NORMALIZE OUTPUT_VARIABLE absolute)
  if(NOT EXISTS "${absolute}")
    message(FATAL_ERROR "scav_embed_bytes: no such file: ${absolute}")
  endif()

  string(TOUPPER "${symbol}" upper)
  file(READ "${absolute}" hex HEX)
  string(LENGTH "${hex}" hex_length)
  math(EXPR byte_count "${hex_length} / 2")
  if(byte_count EQUAL 0)
    message(FATAL_ERROR "scav_embed_bytes: ${absolute} is empty")
  endif()

  # Two passes, and the order matters: convert every byte first, then break
  # lines on whole entries only. A second pass over raw hex pairs would match
  # inside the `0x..,` the first pass just wrote.
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n  "
    body "${body}")

  set(header "${CMAKE_CURRENT_BINARY_DIR}/scav_embed_${symbol}.h")
  file(CONFIGURE OUTPUT "${header}" CONTENT
"// Generated by scav_embed_bytes from ${absolute}. Do not edit.
#ifndef SCAV_EMBED_${upper}_H_INCLUDED
#define SCAV_EMBED_${upper}_H_INCLUDED

#include \"scav/scav_types.h\"

#include <cstdint>

namespace scav {
scav_byte const *${symbol}_bytes(uint32_t &len);
}

#endif
" @ONLY NEWLINE_STYLE LF)

  set(generated "${CMAKE_CURRENT_BINARY_DIR}/scav_embed_${symbol}.cpp")
  # An accessor rather than an extern array, so no other translation unit needs
  # the byte count or a linter exemption to name the blob.
  file(CONFIGURE OUTPUT "${generated}" CONTENT
"// Generated by scav_embed_bytes from ${absolute}. Do not edit.

#include \"scav_embed_${symbol}.h\"

#include <array>

namespace scav {

namespace {

std::array<scav_byte, ${byte_count}> const ${upper}{ {
  ${body}
} };

}  // namespace

scav_byte const *${symbol}_bytes(uint32_t &len) {
  len = ${byte_count}U;
  return ${upper}.data();
}

}  // namespace scav
" @ONLY NEWLINE_STYLE LF)

  # Generated code is not ours to lint or to hold to the warning set.
  set_source_files_properties("${generated}" PROPERTIES
    SKIP_LINTING ON
    COMPILE_OPTIONS ""
  )
  set(${out_var} "${generated}" PARENT_SCOPE)
endfunction()
